name: Deploy ECS

on:
  push:
    branches:
      - candidato/christianmisel3

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ethos-cand-christianmisel3

jobs:

  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:latest \
            ./app-ethos-mock

      - name: Tag Image
        run: |
          docker tag \
          $ECR_REPOSITORY:latest \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

          docker tag \
          $ECR_REPOSITORY:latest \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Images
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Terraform Init
        working-directory: infra/ecs
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/ecs
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/ecs
        run: terraform plan

#        nombre: Terraform Apply
#        directorio de trabajo: infra/ecs
#        run: terraform apply -auto-approve
